name: Build and publish
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Build
        run: npm run build
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/*