name: Build and publish
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Store logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: .npm/_logs/*
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/*
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: dist
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy
        run: |
          set -euo pipefail
          rsync -az --exclude=.git --delete ./build/ ./dist/
          cd dist
          git config user.name "Build Agent"
          git config user.email noreply@github.com
          git add .
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Website publish"
            git push --set-upstream --force origin gh-pages
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}