name: Build and publish
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Store logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: .npm/_logs/*
      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/*